title: 100% Route using Great Eagle Bow with WMC

version: 1.0

route:
  use: ./main.yaml

config:
- use: Pistonight/celer-presets/botw/full.yaml
- plugins:
  - use: link
  - use: variables
- presets:
    _Snap:
      Quest:
        text: $(0)
        icon: camera
        icon-priority: 2
        comment: SNAP for QUEST
